version: '3.1'

services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432"
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_NAME

  server:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgres://$DB_USER:$DB_PASSWORD@db:5432/$DB_NAME
    ports:
      - "8080:8080"
    depends_on:
      - db
